apiVersion: v1
kind: Service
metadata:
  name: mydockerwebapp-service
  labels:
    app: mydockerwebapp
spec:
  type: LoadBalancer # This will provision an Azure Load Balancer
  selector:
    app: mydockerwebapp # This matches the 'app' label in your deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on (external)
      targetPort: 80 # The port your container is listening on (internal, from Dockerfile EXPOSE 80)
